namespace UnityRehamove {
//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class rehamovelib {
  public static int add(int x, int y) {
    int ret = rehamovelibPINVOKE.add(x, y);
    return ret;
  }

  public static RehamoveDevice open_port(string port_name) {
    global::System.IntPtr cPtr = rehamovelibPINVOKE.open_port(port_name);
    RehamoveDevice ret = (cPtr == global::System.IntPtr.Zero) ? null : new RehamoveDevice(cPtr, false);
    return ret;
  }

  public static void close_port(RehamoveDevice r) {
    rehamovelibPINVOKE.close_port(RehamoveDevice.getCPtr(r));
  }

  public static void pulse(RehamoveDevice r, string channel, int current, int pulse_width) {
    rehamovelibPINVOKE.pulse(RehamoveDevice.getCPtr(r), channel, current, pulse_width);
  }

  public static void custom_pulse(RehamoveDevice r, string channel, int num_points, float c0, int w0, float c1, int w1, float c2, int w2, float c3, int w3, float c4, int w4, float c5, int w5, float c6, int w6, float c7, int w7, float c8, int w8, float c9, int w9, float c10, int w10, float c11, int w11, float c12, int w12, float c13, int w13, float c14, int w14, float c15, int w15) {
    rehamovelibPINVOKE.custom_pulse(RehamoveDevice.getCPtr(r), channel, num_points, c0, w0, c1, w1, c2, w2, c3, w3, c4, w4, c5, w5, c6, w6, c7, w7, c8, w8, c9, w9, c10, w10, c11, w11, c12, w12, c13, w13, c14, w14, c15, w15);
  }

  public static int battery(RehamoveDevice r) {
    int ret = rehamovelibPINVOKE.battery(RehamoveDevice.getCPtr(r));
    return ret;
  }

}
}
