# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_rehamovelib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_rehamovelib')
    _rehamovelib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rehamovelib', [dirname(__file__)])
        except ImportError:
            import _rehamovelib
            return _rehamovelib
        try:
            _mod = imp.load_module('_rehamovelib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _rehamovelib = swig_import_helper()
    del swig_import_helper
else:
    import _rehamovelib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Rehamove(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Rehamove, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Rehamove, name)
    __repr__ = _swig_repr
    __swig_setmethods__["port_name"] = _rehamovelib.Rehamove_port_name_set
    __swig_getmethods__["port_name"] = _rehamovelib.Rehamove_port_name_get
    if _newclass:
        port_name = _swig_property(_rehamovelib.Rehamove_port_name_get, _rehamovelib.Rehamove_port_name_set)
    __swig_setmethods__["device"] = _rehamovelib.Rehamove_device_set
    __swig_getmethods__["device"] = _rehamovelib.Rehamove_device_get
    if _newclass:
        device = _swig_property(_rehamovelib.Rehamove_device_get, _rehamovelib.Rehamove_device_set)

    def __init__(self):
        this = _rehamovelib.new_Rehamove()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _rehamovelib.delete_Rehamove
    __del__ = lambda self: None
Rehamove_swigregister = _rehamovelib.Rehamove_swigregister
Rehamove_swigregister(Rehamove)


def open_port(port_name):
    return _rehamovelib.open_port(port_name)
open_port = _rehamovelib.open_port

def close_port(r):
    return _rehamovelib.close_port(r)
close_port = _rehamovelib.close_port

def pulse(r, channel, current, pulse_width):
    return _rehamovelib.pulse(r, channel, current, pulse_width)
pulse = _rehamovelib.pulse

def custom_pulse(r, channel, num_points, c0, w0, c1, w1, c2, w2, c3, w3, c4, w4, c5, w5, c6, w6, c7, w7, c8, w8, c9, w9, c10, w10, c11, w11, c12, w12, c13, w13, c14, w14, c15, w15):
    return _rehamovelib.custom_pulse(r, channel, num_points, c0, w0, c1, w1, c2, w2, c3, w3, c4, w4, c5, w5, c6, w6, c7, w7, c8, w8, c9, w9, c10, w10, c11, w11, c12, w12, c13, w13, c14, w14, c15, w15)
custom_pulse = _rehamovelib.custom_pulse

def battery(r):
    return _rehamovelib.battery(r)
battery = _rehamovelib.battery
# This file is compatible with both classic and new-style classes.


